config/routes.rb
Rails.application.routes.draw do

  root 'reservations#index'

  post "reservations/new", to: "reservations#create"

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :table

  validates_presence_of :name, :table, :num_of_seats_reserved, :reservation_date, :hour

  validates_inclusion_of :hour, in: 0..23

  validates :num_of_seats_reserved, numericality: { greater_than_or_equal_to: 0 }

  def self.make_reservation(available_tables, reservation_params)

    seats_needed = reservation_params[:num_of_seats_reserved].to_i

    while seats_needed > 0
      if need_more_seats(available_tables[-1], seats_needed)
        book_table(reservation_params, available_tables[-1])
      else
        available_tables.each do |table|
          book_table(reservation_params, table) if !need_more_seats(table, seats_needed)
          break
        end
      end
      seats_needed -= available_tables[-1].num_of_seats
      available_tables.pop
    end
  end

  def self.book_table(reservation_params, table_to_book)
    @reservation = Reservation.new(name: reservation_params[:name], table: table_to_book, num_of_seats_reserved: reservation_params[:num_of_seats_reserved], reservation_date: reservation_params[:reservation_date], hour: reservation_params[:hour])
    @reservation.save
  end

  def self.need_more_seats(table, seats_needed)
    table.num_of_seats <= seats_needed
  end

end

app/models/table.rb
class Table < ActiveRecord::Base
  has_many :reservations

  validates_presence_of :number, :num_of_seats

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = Reservation.all.order('reservation_date, hour, name')
  end

  def create
    # I know this adds an additional query to find the available tables, but for some reason I could not get where.not to work for this query.
    reserved_tables = Table.joins(:reservations).merge(Reservation.where(reservation_date: reservation_params[:reservation_date], hour: reservation_params[:hour]))
    all_tables = Table.all.order(:num_of_seats)
    available_tables = all_tables - reserved_tables

    total_capacity_available = available_tables.inject(0) { |sum, tables| sum + tables[:num_of_seats] }

    if total_capacity_available < reservation_params[:num_of_seats_reserved].to_i
      flash[:alert] = "Reservation Failed: Seating Capacity Exceeded"
    else
      Reservation.make_reservation(available_tables, reservation_params)
      flash[:notice] = "Reservation has successfully been created"
    end
    redirect_to root_path
  end

  private
  def reservation_params
    params.require(:reservation).permit(:name, :num_of_seats_reserved, :reservation_date, :hour)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant Reservations</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <span class="navbar-text">
        <h4>Restaurant Reservations</h4>
      </span>
    </div>
  </nav>

  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>

<%= yield %>

</body>
</html>

app/views/reservations/index.html.erb
<div class="container">
  <h2>New Reservation</h2><br>
  <%= form_for :reservation, url: reservations_new_path, class: "form-inline" do |f| %>
    <div class="form-group row">
      <%= f.label :name, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-4">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "Seats to Reserve", class: "col-sm-2 col-form-label"  %>
      <div class="col-sm-4">
        <%= f.number_field :num_of_seats_reserved, class: 'form-control mb-2 mr-sm-2 mb-sm-0' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :reservation_date, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-4">
        <%= f.date_field :reservation_date, class: 'form-control mb-2 mr-sm-2 mb-sm-0' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "Reservation Time (0-23)", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-4">
        <%= f.number_field :hour, class: 'form-control mb-2 mr-sm-2 mb-sm-0' %>
      </div>
    </div>
      <div class="form-group row">
        <div class="col-sm-10">
          <%= f.submit "Submit", class: 'btn btn-success' %><br>
        </div>
      </div>
  <% end %><br><br>

  <h2>Reservations</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Table Number</th>
          <th>Seats Reserved</th>
          <th>Reservation Date</th>
          <th>Reservation Time</th>
        </tr>
      </thead>
      <tbody>
        <% @reservations.each do |reserv| %>
        <tr>
          <td><%= reserv.name %></td>
          <td><%= reserv.table.number %></td>
          <td><%= reserv.num_of_seats_reserved %></td>
          <td><%= reserv.reservation_date.strftime("%m/%d/%Y") %></td>
          <% if reserv.hour == 0 %>
            <td>12:00 AM</td>
          <% elsif reserv.hour == 12 %>
              <td>12:00 PM</td>
          <% elsif reserv.hour < 12 %>
            <td><%= reserv.hour %>:00 AM</td>
          <% elsif reserv.hour > 12 %>
            <td><%= reserv.hour - 12 %>:00 PM</td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>

</div>